<?php
/**
 * User login
 *
 * @see ManneBusk_DevPanel_Block_Tab_Userlogin
 */
    $help           = Mage::helper('devpanel');
    $frontendUsers  = Mage::getModel('customer/customer')
        ->getCollection()
        ->addAttributeToSelect(array('firstname', 'lastname'));
    $adminUsers     = Mage::getModel('admin/user')
        ->getCollection();
    $urlModel = Mage::getModel('core/url');
?>
<div class="devpanel-content" data-tools-tabcontent="<?php echo $this->getNameInLayout() ?>">
    <div class="col" id="frontend-login-list">
        <div class="menu-bar">
            <input type="search" class="user-frontend-input" data-loginfrontend-input placeholder="Frontend Users">
            <a class="button icon" data-search-clear><?php echo $help->getIcon('adminui/cross93') ?></a>
        </div>

        <ul class="devpanel-detail-list list" >
            <?php foreach ($frontendUsers as $user) : ?>
                <li>
                    <a href="<?php echo Mage::getUrl('devpanel/login/frontend', array('_query' => array('user' => $user->getEmail()))) ?>">
                        <div class="name"><?php echo $user->getFirstname() ?> <?php echo $user->getLastname() ?></div>
                        <div class="email"><?php echo $user->getEmail()  ?></div>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>

    <div class="col" id="admin-login-list">
        <div class="menu-bar">
            <input type="search" class="user-admin-input" data-loginadmin-input placeholder="Admin Users">
            <a class="button icon" data-search-clear><?php echo $help->getIcon('adminui/cross93') ?></a>
        </div>

        <ul class="devpanel-detail-list list" >
            <?php foreach ($adminUsers as $user) : ?>
                <li>
                    <a href="<?php echo $urlModel->getUrl('adminhtml/dashboard', array('_query' => array('user' => $user->getUsername()))) ?>">
                        <div class="name"><?php echo $user->getUsername() ?></div>
                        <div class="email"><?php echo $user->getEmail()  ?></div>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>

