<?php
/**
 * Layout Tab
 *
 * @see ManneBusk_DevPanel_Block_Tab_Layout
 */
    $help = Mage::helper('devpanel');
?>
<div class="devpanel-content">
    <div class="col" id="layout-handle-list">
        <div class="menu-bar">
            <input type="search" class="layout-handle-search" placeholder="Layout Handles">
            <a class="button icon" data-search-clear><?php echo $help->getIcon('adminui/cross93') ?></a>
        </div>
        <ul class="devpanel-detail-list list">
            <?php foreach ($this->getLayout()->getUpdate()->getHandles() as $handle) : ?>
                <li>
                    <span class="handle"><?php echo $handle ?></span>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>

    <div class="col" id="block-info-list">
        <div class="menu-bar">
            <input type="search" class="block-info-search" placeholder="Loaded blocks">
            <a class="button icon" data-toggle-hints><?php echo $help->getIcon('adminui/visible9') ?></a>
            <a class="button icon" data-hints-off data-search-clear><?php echo $help->getIcon('adminui/cross93') ?></a>
        </div>

        <ul class="devpanel-detail-list list" >
            <?php foreach ($this->getBlockInfo() as $info) : ?>
                <li>
                    <h4>
                        <span class="name"><?php echo $info->getName() ?></span>
                        <?php if ($info->getAlias() && $info->getAlias() != $info->getName()) : ?>
                            <span class="alias muted">(<?php echo $info->getAlias() ?>)</span>
                        <?php endif; ?>

                    </h4>
                    <dl>
                        <dt><?php echo $this->__('Class') ?>:</dt>
                        <dd class="class"><?php echo $info->getClass() ?></dd>

                        <?php if ($info->getTemplate()) : ?>
                        <dt><?php echo $this->__('Template') ?>:</dt>
                        <dd class="template"><?php echo $info->getTemplate() ?></dd>
                        <?php endif; ?>

                    </dl>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>

