<?php
/**
 * Tools Panel
 *
 * @see ManneBusk_DevPanel_Block_Tab
 */
    $formFillData   = $this->getAutoFill();
    $help           = Mage::helper('devpanel');
?>
<?php $this->getEntityInfo() ?>
<nav class="devpanel-side-nav" data-tabcontroller="tools">
    <ul>
        <li><a data-devpanel-ajax href="<?php echo Mage::getUrl('devpanel/cache/clear') ?>">Clear Cache</a></li>

        <?php foreach ($this->getTabs() as $name => $tab) : ?>
            <li data-tools-tab="<?php echo $name ?>" <?php echo $tab->isActive() ? 'class="active"' : '' ?>>
                <a href="#sec-tools"><?php echo $tab->getTitle() ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
</nav>

<?php foreach ($this->getTabs() as $name => $tab) : ?>
    <?php echo $this->getChildHtml($name) ?>
<?php endforeach; ?>
